# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DevFest Florida
email: organizers@devfestflorida.org
description: "DevFest Florida is the first combined DevFest being organized by three Google Developer Groups in the central Florida area: Space Coast, Central Florida, and Tampa Bay."
keywords: "event, gdg, gde, devfest, google, programming, android, chrome, polymer, developers, web, cloud, androiddev, ai, machinelearning, tensorflow, webassembly, web"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devfestflorida.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/sponsors/", text: "Sponsor"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/organizers/", text: "Organizers"}
 
